complete task
BabenkoMaksym/goit-final-project pull request #3
Opened 2023-05-04 16:44 UTC by SellerRyba

create new migration, entity and repository

2023-05-04 21:40 UTC, ShadowInSpace requested changes
Дещо тре доадати а за міграції хай Максим гляне.

2023-05-04 21:40 UTC, ShadowInSpace commented on src/main/java/ua/goit/finalProj2/notes/entity/Note.java
> +@Table(name = "notes")
треба додати схему  schema = "final_project"

2023-05-04 21:40 UTC, ShadowInSpace commented on src/main/java/ua/goit/finalProj2/notes/entity/Note.java
> +    private User user;
Тут треба додати "@ToString.Exclude" щоб не йшло в петлю по ту стрінгу.

2023-05-05 06:00 UTC, BabenkoMaksym reviewed
Потрібно доопрацювати)

2023-05-05 09:38 UTC, BabenkoMaksym approved these changes

2023-05-05 09:38 UTC, BabenkoMaksym approved these changes

2023-05-05 10:00 UTC, ShadowInSpace approved these changes

2023-05-05 10:12 UTC, ShadowInSpace approved these changes

2023-05-05 10:12 UTC, BabenkoMaksym approved these changes

2023-05-05 10:14 UTC, merged